import '../models/vehicle_model.dart';

class VehicleService {
  /// Local catalog of EV models with verified specifications for Phase 4 Step 2A.
  static final List<VehicleModel> indianEVEcosystem = [
    const VehicleModel(
      id: 'tata-nexon-ev-lr',
      manufacturer: 'Tata',
      model: 'Nexon EV',
      variant: 'Long Range (40.5 kWh)',
      year: 2024,
      batteryCapacity: 40.5,
      usableBatteryCapacityKWh: 40.5,
      realRange: 290.0,
      averageEfficiency: 140.0, // Wh/km
      connectorTypes: ['CCS2', 'Type 2'],
      maxAcChargingSpeed: 7.2,
      maxDcChargingSpeed: 50.0,
      vehicleImage: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=800&q=80',
      registrationNumber: 'DL-3C-AY-1244',
      nickname: 'Nexon EV',
      isDefault: true,
      currentBatteryPct: 80.0,
    ),
    const VehicleModel(
      id: 'tata-punch-ev',
      manufacturer: 'Tata',
      model: 'Punch EV',
      variant: 'Long Range (35 kWh)',
      year: 2024,
      batteryCapacity: 35.0,
      usableBatteryCapacityKWh: 35.0,
      realRange: 270.0,
      averageEfficiency: 130.0,
      connectorTypes: ['CCS2', 'Type 2'],
      maxAcChargingSpeed: 7.2,
      maxDcChargingSpeed: 50.0,
      vehicleImage: 'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&w=800&q=80',
      registrationNumber: 'DL-4C-EV-1002',
      nickname: 'Punch EV',
      currentBatteryPct: 80.0,
    ),
    const VehicleModel(
      id: 'tata-tiago-ev',
      manufacturer: 'Tata',
      model: 'Tiago EV',
      variant: 'Long Range (24 kWh)',
      year: 2024,
      batteryCapacity: 24.0,
      usableBatteryCapacityKWh: 24.0,
      realRange: 200.0,
      averageEfficiency: 120.0,
      connectorTypes: ['CCS2', 'Type 2'],
      maxAcChargingSpeed: 7.2,
      maxDcChargingSpeed: 50.0,
      vehicleImage: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
      registrationNumber: 'DL-5C-EV-2003',
      nickname: 'Tiago EV',
      currentBatteryPct: 80.0,
    ),
    const VehicleModel(
      id: 'mg-zs-ev',
      manufacturer: 'MG',
      model: 'ZS EV',
      variant: 'Excite (50.3 kWh)',
      year: 2024,
      batteryCapacity: 50.3,
      usableBatteryCapacityKWh: 50.3,
      realRange: 335.0,
      averageEfficiency: 150.0,
      connectorTypes: ['CCS2', 'Type 2'],
      maxAcChargingSpeed: 7.4,
      maxDcChargingSpeed: 50.0,
      vehicleImage: 'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&w=800&q=80',
      registrationNumber: 'MH-12-TX-8899',
      nickname: 'ZS EV',
      currentBatteryPct: 80.0,
    ),
    const VehicleModel(
      id: 'mg-comet-ev',
      manufacturer: 'MG',
      model: 'Comet EV',
      variant: 'Pace (17.3 kWh)',
      year: 2024,
      batteryCapacity: 17.3,
      usableBatteryCapacityKWh: 17.3,
      realRange: 180.0,
      averageEfficiency: 95.0,
      connectorTypes: ['Type 2'],
      maxAcChargingSpeed: 3.3,
      maxDcChargingSpeed: 3.3,
      vehicleImage: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
      registrationNumber: 'MH-02-EV-4400',
      nickname: 'Comet EV',
      currentBatteryPct: 80.0,
    ),
    const VehicleModel(
      id: 'mahindra-xuv400',
      manufacturer: 'Mahindra',
      model: 'XUV400 EV',
      variant: 'EL Pro (39.4 kWh)',
      year: 2024,
      batteryCapacity: 39.4,
      usableBatteryCapacityKWh: 39.4,
      realRange: 270.0,
      averageEfficiency: 145.0,
      connectorTypes: ['CCS2', 'Type 2'],
      maxAcChargingSpeed: 7.2,
      maxDcChargingSpeed: 50.0,
      vehicleImage: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
      registrationNumber: 'MH-14-EV-0400',
      nickname: 'XUV400 EV',
      currentBatteryPct: 80.0,
    ),
    const VehicleModel(
      id: 'hyundai-ioniq-5',
      manufacturer: 'Hyundai',
      model: 'Ioniq 5',
      variant: 'RWD (72.6 kWh)',
      year: 2024,
      batteryCapacity: 72.6,
      usableBatteryCapacityKWh: 72.6,
      realRange: 450.0,
      averageEfficiency: 160.0,
      connectorTypes: ['CCS2', 'Type 2'],
      maxAcChargingSpeed: 11.0,
      maxDcChargingSpeed: 350.0,
      vehicleImage: 'https://images.unsplash.com/photo-1669062508887-21be148970e5?auto=format&fit=crop&w=800&q=80',
      registrationNumber: 'DL-1C-EV-9999',
      nickname: 'Ioniq 5',
      currentBatteryPct: 80.0,
    ),
    const VehicleModel(
      id: 'kia-ev6',
      manufacturer: 'Kia',
      model: 'EV6',
      variant: 'GT-Line (77.4 kWh)',
      year: 2024,
      batteryCapacity: 77.4,
      usableBatteryCapacityKWh: 77.4,
      realRange: 480.0,
      averageEfficiency: 165.0,
      connectorTypes: ['CCS2', 'Type 2'],
      maxAcChargingSpeed: 11.0,
      maxDcChargingSpeed: 350.0,
      vehicleImage: 'https://images.unsplash.com/photo-1669062508887-21be148970e5?auto=format&fit=crop&w=800&q=80',
      registrationNumber: 'KA-01-EV-6600',
      nickname: 'EV6',
      currentBatteryPct: 80.0,
    ),
    const VehicleModel(
      id: 'byd-atto-3',
      manufacturer: 'BYD',
      model: 'Atto 3',
      variant: 'Extended Range (60.48 kWh)',
      year: 2024,
      batteryCapacity: 60.48,
      usableBatteryCapacityKWh: 60.48,
      realRange: 400.0,
      averageEfficiency: 155.0,
      connectorTypes: ['CCS2', 'Type 2'],
      maxAcChargingSpeed: 7.0,
      maxDcChargingSpeed: 80.0,
      vehicleImage: 'https://images.unsplash.com/photo-1681283620953-73c38db5dfc8?auto=format&fit=crop&w=800&q=80',
      registrationNumber: 'KA-03-MY-7722',
      nickname: 'Atto 3',
      currentBatteryPct: 80.0,
    ),
    const VehicleModel(
      id: 'byd-seal',
      manufacturer: 'BYD',
      model: 'Seal',
      variant: 'Premium (82.56 kWh)',
      year: 2024,
      batteryCapacity: 82.56,
      usableBatteryCapacityKWh: 82.56,
      realRange: 520.0,
      averageEfficiency: 160.0,
      connectorTypes: ['CCS2', 'Type 2'],
      maxAcChargingSpeed: 7.0,
      maxDcChargingSpeed: 150.0,
      vehicleImage: 'https://images.unsplash.com/photo-1681283620953-73c38db5dfc8?auto=format&fit=crop&w=800&q=80',
      registrationNumber: 'TN-09-EV-8800',
      nickname: 'BYD Seal',
      currentBatteryPct: 80.0,
    ),
  ];

  Future<List<VehicleModel>> getAvailableVehicles() async {
    return indianEVEcosystem;
  }

  Future<VehicleModel?> getVehicleById(String id) async {
    try {
      return indianEVEcosystem.firstWhere((v) => v.id == id);
    } catch (e) {
      return null;
    }
  }
}
