/// RecommendedChargingStop
///
/// Represents a single recommended charging stop along a planned EV route.
/// Generated by [ChargingStopRecommendationService].
library;

import 'map_marker_model.dart';

/// Why this stop was recommended.
enum ChargingStopReason {
  /// Battery would drop below safety reserve without this stop.
  batteryTooLow,

  /// No other compatible charger within reachable range ahead.
  noChargerAhead,

  /// Opportunistic top-up to ensure comfortable arrival.
  opportunisticTopUp,
}

class RecommendedChargingStop {
  /// The EV charger at this stop.
  final MapMarkerModel charger;

  /// Distance from the trip start (origin) to this charger, in km.
  final double distanceFromStartKm;

  /// Remaining distance from this charger to the destination, in km.
  final double distanceToDestinationKm;

  /// Estimated battery level (%) when arriving at this charger.
  final double estimatedArrivalBatteryPct;

  /// Recommended battery level (%) to charge up to before leaving.
  final double recommendedChargingTargetPct;

  /// Estimated energy that needs to be added at this stop, in kWh.
  final double estimatedChargingEnergyKWh;

  /// Estimated time to charge from arrival % to target %, in minutes.
  final double estimatedChargingDurationMinutes;

  /// Human-readable reason for this recommendation.
  final ChargingStopReason reason;

  /// Stop index (1-based) in the recommended plan.
  final int stopIndex;

  /// Whether this stop uses a compatible connector for the selected vehicle.
  final bool isCompatible;

  // -- Phase 4 Step 3 Cost & Energy additions --
  /// Energy needed for this specific leg (origin or previous stop to here).
  final double energyNeededForStopKwh;

  /// Energy physically drawn from the grid (includes charging losses).
  final double gridEnergyDrawnKwh;

  /// Charging loss (gridEnergyDrawnKwh - estimatedChargingEnergyKWh).
  final double chargingLossKwh;

  /// Price per kWh applied at this stop (null if unavailable).
  final double? pricePerKwh;

  /// Estimated cost for this charging stop.
  final double estimatedChargingCost;

  /// Source of the tariff used ('Station tariff', 'Network tariff', 'Estimated tariff', 'Price unavailable').
  final String tariffSource;

  const RecommendedChargingStop({
    required this.charger,
    required this.distanceFromStartKm,
    required this.distanceToDestinationKm,
    required this.estimatedArrivalBatteryPct,
    required this.recommendedChargingTargetPct,
    required this.estimatedChargingEnergyKWh,
    required this.estimatedChargingDurationMinutes,
    required this.reason,
    required this.stopIndex,
    this.isCompatible = true,
    this.energyNeededForStopKwh = 0.0,
    this.gridEnergyDrawnKwh = 0.0,
    this.chargingLossKwh = 0.0,
    this.pricePerKwh,
    this.estimatedChargingCost = 0.0,
    this.tariffSource = 'Price unavailable',
  });

  /// Estimated battery gain at this stop (target − arrival).
  double get batteryGainPct =>
      recommendedChargingTargetPct - estimatedArrivalBatteryPct;

  /// Energy added to battery (alias for estimatedChargingEnergyKWh).
  double get energyAddedToBatteryKwh => estimatedChargingEnergyKWh;

  /// User-friendly reason string.
  String get reasonLabel {
    switch (reason) {
      case ChargingStopReason.batteryTooLow:
        return 'Battery too low to reach next stop safely';
      case ChargingStopReason.noChargerAhead:
        return 'No compatible charger within reachable range ahead';
      case ChargingStopReason.opportunisticTopUp:
        return 'Opportunistic top-up for comfortable arrival';
    }
  }

  /// Rounded estimated charging duration in minutes.
  int get estimatedChargingDurationMinutesInt =>
      estimatedChargingDurationMinutes.ceil();

  @override
  String toString() =>
      'RecommendedChargingStop(#$stopIndex, ${charger.title}, '
      '${distanceFromStartKm.toStringAsFixed(1)} km, '
      'arrival: ${estimatedArrivalBatteryPct.toStringAsFixed(0)}%, '
      'target: ${recommendedChargingTargetPct.toStringAsFixed(0)}%, '
      '~$estimatedChargingDurationMinutesInt min, cost: ₹${estimatedChargingCost.toStringAsFixed(2)})';
}

/// Complete smart trip result returned after route analysis.
class SmartTripResult {
  /// All recommended charging stops (ordered by distance from origin).
  final List<RecommendedChargingStop> recommendedStops;

  /// Trip distance in km.
  final double tripDistanceKm;

  /// Energy required for the full trip in kWh (driving energy).
  final double tripEnergyRequiredKWh;

  /// Battery percentage needed (without charging) to complete the trip.
  final double requiredBatteryPct;

  /// Estimated battery % at destination (if stops are followed).
  final double estimatedBatteryAtDestinationPct;

  /// Whether charging is required (true = at least one stop needed).
  final bool chargingRequired;

  /// Whether any compatible charger was found along the route.
  final bool compatibleChargerFound;

  // -- Phase 4 Step 3 Cost & Energy additions --
  /// Total energy added to the battery across all stops.
  final double totalEnergyAddedKwh;

  /// Total grid energy drawn across all stops.
  final double totalGridEnergyKwh;

  /// Total charging losses across all stops.
  final double totalChargingLossKwh;

  /// Total estimated charging cost.
  final double totalChargingCost;

  /// Average cost per km.
  final double averageCostPerKm;

  /// Estimated cost per 100 km.
  final double costPer100Km;

  /// Total estimated additional time from charging stops (minutes).
  double get totalChargingTimeMinutes => recommendedStops.fold(
        0.0,
        (sum, stop) => sum + stop.estimatedChargingDurationMinutes,
      );

  const SmartTripResult({
    required this.recommendedStops,
    required this.tripDistanceKm,
    required this.tripEnergyRequiredKWh,
    required this.requiredBatteryPct,
    required this.estimatedBatteryAtDestinationPct,
    required this.chargingRequired,
    required this.compatibleChargerFound,
    this.totalEnergyAddedKwh = 0.0,
    this.totalGridEnergyKwh = 0.0,
    this.totalChargingLossKwh = 0.0,
    this.totalChargingCost = 0.0,
    this.averageCostPerKm = 0.0,
    this.costPer100Km = 0.0,
  });

  /// Alias for driving energy
  double get totalDrivingEnergyKwh => tripEnergyRequiredKWh;

  /// Quick status: green / orange / red for UI.
  SmartTripStatus get status {
    if (!chargingRequired) return SmartTripStatus.tripPossible;
    if (recommendedStops.isNotEmpty) return SmartTripStatus.chargingRecommended;
    return SmartTripStatus.chargingRequired;
  }
}

enum SmartTripStatus {
  /// Trip is possible without charging.
  tripPossible,

  /// Charging is recommended and suitable stops found.
  chargingRecommended,

  /// Charging is required (stops found or not found).
  chargingRequired,
}
