// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEo5B22e8tT6UUIMgI8BA_jXLdLMQsmAg',
    appId: '1:211167795372:web:c41d97ccea2abe04fe6709',
    messagingSenderId: '211167795372',
    projectId: 'evhub-9e25f',
    authDomain: 'evhub-9e25f.firebaseapp.com',
    storageBucket: 'evhub-9e25f.firebasestorage.app',
    measurementId: 'G-1QT3R9G61B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjqJ8tHsVPfyEVrOYXD3oM3hJw65dqpic',
    appId: '1:211167795372:android:cad61d54242d6f41fe6709',
    messagingSenderId: '211167795372',
    projectId: 'evhub-9e25f',
    storageBucket: 'evhub-9e25f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh8BvIyAWKsnGxIkOJZfBjHAsiEFO_2cs',
    appId: '1:211167795372:ios:71e31f7e10af619bfe6709',
    messagingSenderId: '211167795372',
    projectId: 'evhub-9e25f',
    storageBucket: 'evhub-9e25f.firebasestorage.app',
    iosClientId: '211167795372-g54sp5enn6t4fpiv8pcv73j40cck4mhb.apps.googleusercontent.com',
    iosBundleId: 'com.evhub.evhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh8BvIyAWKsnGxIkOJZfBjHAsiEFO_2cs',
    appId: '1:211167795372:ios:71e31f7e10af619bfe6709',
    messagingSenderId: '211167795372',
    projectId: 'evhub-9e25f',
    storageBucket: 'evhub-9e25f.firebasestorage.app',
    iosClientId: '211167795372-g54sp5enn6t4fpiv8pcv73j40cck4mhb.apps.googleusercontent.com',
    iosBundleId: 'com.evhub.evhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEo5B22e8tT6UUIMgI8BA_jXLdLMQsmAg',
    appId: '1:211167795372:web:2ce4bccac58198f6fe6709',
    messagingSenderId: '211167795372',
    projectId: 'evhub-9e25f',
    authDomain: 'evhub-9e25f.firebaseapp.com',
    storageBucket: 'evhub-9e25f.firebasestorage.app',
    measurementId: 'G-9SNY46XEKR',
  );
}
